unique_ids:
  assets:
    standard-page.html: IMWUIAMNRRUK64GSB3ORGM2QHX6CVR2B
    theme.css: UBNNYL5WWX3Z7RSNCLWEF3KZQYCDZ3EL
  forms:
    Form1: H332S7KZS6GEPS3VGAE365FH43EJ5MQK
  modules: {}
  scripts: {}
  server_modules: {}
